---
title: "South Region - Richmond Times Dispatch"
author: "Samarth Saxena"
date: "10/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(tidyverse)
#install.packages("tidytext")
library(tidytext)
#install.packages("ggwordcloud")
library(ggwordcloud)
install.packages("gutenbergr") 
library(gutenbergr)
#install.packages('textdata')
library(textdata)
#setwd("/cloud/project/tidytext")
#save.image("tidytext.RData")

```

```{r}
get_sentiments('afinn')# we see a list of words and there classification, 2,467 - not really that many overall. 

get_sentiments('nrc')# looks like a good amount more 13,891, but as we can see words are classified in several different categories. 

get_sentiments('bing')# looks like a good amount more 6,776, but as we can see just negative and positive. 

convert <- function(x){
  x <- tibble(x)
  x$x <- as.character(x$x)
  x <- x %>%
  unnest_tokens(word, x)%>%
  anti_join(stop_words)%>% 
  count(word, sort=TRUE)
}

wordcloud <- function(x){
  set.seed(42)
  ggplot(x[1:50, ], aes(label = word, size = n)
       ) +
    geom_text_wordcloud() +
    theme_minimal()
}
afinnplot <- function(y){
  ggplot(data = y, 
       aes(x = value)
        )+
  geom_histogram()+
  ggtitle("Sentiment Range")+
  theme_minimal()
}

bingplot <- function(y){
  ggplot(data = y, 
       aes(x= sentiment, y = n)
        )+
  geom_point()+
  ggtitle("Sentiment Range")+
  theme_minimal()
}
nrcplot <- function(y){
  ggplot(data = y, 
       aes(x= sentiment, y = n)
        )+
  geom_point()+
  ggtitle("Sentiment Frequency")+
  theme_minimal()
}

news1 <- read_lines("news1.txt")
news2 <- read_lines("news2.txt")
news3 <- read_lines("news3.txt")
news4 <- read_lines("news4.txt")
news5 <- read_lines("news5.txt")
news6 <- read_lines("news6.txt")
news7 <- read_lines("news7.txt")
news8 <- read_lines("news8.txt")
news9 <- read_lines("news9.txt")
news10 <- read_lines("news10.txt")

news1 <- convert(news1)
news2 <- convert(news2)
news3 <- convert(news3)
news4 <- convert(news4)
news5 <- convert(news5)
news6 <- convert(news6)
news7 <- convert(news7)
news8 <- convert(news8)
news9 <- convert(news9)
news10 <- convert(news10)

wordcloud1 <- wordcloud(news1)
wordcloud2 <- wordcloud(news2)
wordcloud3 <- wordcloud(news3)
wordcloud4 <- wordcloud(news4)
wordcloud5 <- wordcloud(news5)
wordcloud6 <- wordcloud(news6)
wordcloud7 <- wordcloud(news7)
wordcloud8 <- wordcloud(news8)
wordcloud9 <- wordcloud(news9)
wordcloud10 <- wordcloud(news10)

news1_afinn <- news1 %>%
  inner_join(get_sentiments("afinn"))
  
news1_nrc <- news1 %>%
  inner_join(get_sentiments("nrc"))

news1_bing <- news1 %>%
  inner_join(get_sentiments("bing"))

news2_afinn <- news2 %>%
  inner_join(get_sentiments("afinn"))
  
news2_nrc <- news2 %>%
  inner_join(get_sentiments("nrc"))

news2_bing <- news2 %>%
  inner_join(get_sentiments("bing"))

news3_afinn <- news3 %>%
  inner_join(get_sentiments("afinn"))
  
news3_nrc <- news3 %>%
  inner_join(get_sentiments("nrc"))

news3_bing <- news3 %>%
  inner_join(get_sentiments("bing"))

news4_afinn <- news4 %>%
  inner_join(get_sentiments("afinn"))
  
news4_nrc <- news4 %>%
  inner_join(get_sentiments("nrc"))

news4_bing <- news4 %>%
  inner_join(get_sentiments("bing"))

news5_afinn <- news5 %>%
  inner_join(get_sentiments("afinn"))
  
news5_nrc <- news5 %>%
  inner_join(get_sentiments("nrc"))

news5_bing <- news5 %>%
  inner_join(get_sentiments("bing"))

news6_afinn <- news6 %>%
  inner_join(get_sentiments("afinn"))
  
news6_nrc <- news6 %>%
  inner_join(get_sentiments("nrc"))

news6_bing <- news6 %>%
  inner_join(get_sentiments("bing"))

news7_afinn <- news7 %>%
  inner_join(get_sentiments("afinn"))
  
news7_nrc <- news7 %>%
  inner_join(get_sentiments("nrc"))

news7_bing <- news7 %>%
  inner_join(get_sentiments("bing"))

news8_afinn <- news8 %>%
  inner_join(get_sentiments("afinn"))
  
news8_nrc <- news8 %>%
  inner_join(get_sentiments("nrc"))

news8_bing <- news8 %>%
  inner_join(get_sentiments("bing"))

news9_afinn <- news9 %>%
  inner_join(get_sentiments("afinn"))
  
news9_nrc <- news9 %>%
  inner_join(get_sentiments("nrc"))

news9_bing <- news9 %>%
  inner_join(get_sentiments("bing"))

news10_afinn <- news10 %>%
  inner_join(get_sentiments("afinn"))
  
news10_nrc <- news10 %>%
  inner_join(get_sentiments("nrc"))

news10_bing <- news10 %>%
  inner_join(get_sentiments("bing"))

afinn1 <- afinnplot(news1_afinn)
bing1 <- bingplot(news1_bing)
nrc1 <- nrcplot(news1_nrc)
afinn2 <- afinnplot(news2_afinn)
bing2 <- bingplot(news2_bing)
nrc2 <- nrcplot(news2_nrc)
afinn3 <- afinnplot(news3_afinn)
bing3 <- bingplot(news3_bing)
nrc3 <- nrcplot(news3_nrc)
afinn4 <- afinnplot(news4_afinn)
bing4 <- bingplot(news4_bing)
nrc4 <- nrcplot(news4_nrc)
afinn5 <- afinnplot(news5_afinn)
bing5 <- bingplot(news5_bing)
nrc5 <- nrcplot(news5_nrc)
afinn6 <- afinnplot(news6_afinn)
bing6 <- bingplot(news6_bing)
nrc6 <- nrcplot(news6_nrc)
afinn7 <- afinnplot(news7_afinn)
bing7 <- bingplot(news7_bing)
nrc7 <- nrcplot(news7_nrc)
afinn8 <- afinnplot(news8_afinn)
bing8 <- bingplot(news8_bing)
nrc8 <- nrcplot(news8_nrc)
afinn9 <- afinnplot(news9_afinn)
bing9 <- bingplot(news9_bing)
nrc9 <- nrcplot(news9_nrc)
afinn10 <- afinnplot(news10_afinn)
bing10 <- bingplot(news10_bing)
nrc10 <- nrcplot(news10_nrc)
```

### TF IDF
```{r}
data_prep <- function(x,y,z){
  i <- as_tibble(t(x))
  ii <- unite(i,"text",y:z,remove = TRUE,sep = "")
}
news1raw <- read_lines("news1.txt")
news2raw <- read_lines("news2.txt")
news3raw <- read_lines("news3.txt")
news4raw <- read_lines("news4.txt")
news5raw <- read_lines("news5.txt")
news6raw <- read_lines("news6.txt")
news7raw <- read_lines("news7.txt")
news8raw <- read_lines("news8.txt")
news9raw <- read_lines("news9.txt")
news10raw <- read_lines("news10.txt")

news1bag <- data_prep(news1raw, 'V1', 'V29')
news2bag <- data_prep(news2raw, 'V1', 'V30')
news3bag <- data_prep(news3raw, 'V1', 'V34')
news4bag <- data_prep(news4raw, 'V1', 'V20')
news5bag <- data_prep(news5raw, 'V1', 'V23')
news6bag <- data_prep(news6raw, 'V1', 'V22')
news7bag <- data_prep(news7raw, 'V1', 'V27')
news8bag <- data_prep(news8raw, 'V1', 'V22')
news9bag <- data_prep(news9raw, 'V1', 'V22')
news10bag <- data_prep(news10raw, 'V1', 'V33')

names <- c("Article 1","Article 2","Article 3", "Article 4","Article 5","Article 6", "Article 7","Article 8","Article 9", "Article 10")

tf_idf_text <- tibble(names,text=t(tibble(news1bag,news2bag,news3bag,news4bag,news5bag,news6bag,news7bag,news8bag,news9bag,news10bag,.name_repair = "universal")))

View(tf_idf_text)

word_count <- tf_idf_text %>%
  unnest_tokens(word, text) %>%
  count(names, word, sort = TRUE)


total_words <- word_count %>% 
  group_by(names) %>% 
  summarize(total = sum(n))

article_words <- left_join(word_count, total_words)


article_words <- article_words %>%
  anti_join(stop_words) %>%
  bind_tf_idf(word, names, n)

view(article_words)

totalwordcloud <- wordcloud(article_words)
totalwordcloud

article_words_afinn <- article_words %>%
  inner_join(get_sentiments("afinn"))
afinnplot(article_words_afinn)

write_csv(article_words, "south_words.csv")
```